repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,mdx']
  # for markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
    - id: prettier
      types_or: [html, css, javascript, markdown, mdx]
      args: [--print-width=120, --tab-width=4, --single-quote]
